### ISSUE TITLE
failedConnectionCallback not working.

### ISSUE THREAD

**Issue by der1igedon** [gqty-dev/gqty#1508]
Hello,

I try to get a callback when a subscription to a GraphQL server is not possible in case a websocket connection fails. Right no I try to do it this way (in react):

```
const subscriptionsClient =
  typeof window !== "undefined"
    ? createSubscriptionsClient({
        wsEndpoint: () => {
          // Modify if needed
          const url = new URL(
            "http://localhost:8080/query",
            window.location.href
          );
          url.protocol = url.protocol.replace("http", "ws");
          return url.href;
        },
        failedConnectionCallback: (payload) => {
            console.log("callback called");
          return new Promise(async (resolve, reject) => {
            resolve();
          });
        },
        failedReconnectCallback: () => {
          console.log("callback called");
        },
      })
    : undefined;
```

The two functions `failedConnectionCallback` and `failedReconnectCallback` should catch such cases. but nothing happens if the websocket connection is not available. 

Can anyone help me? Thanks!

**Comment by vicary** [comment]
@der1igedon Our new core is coming to beta, please feel free to read our updated docs at https://gqty.dev and try it out.

The new core uses `graphql-ws` for subscriptions, which is better maintained than the deprecating pacakge`@gqty/subscriptions`.

In your newly generated client, instead of `failedConnectionCallback`, you may now listen to the `error` event.

```ts
subscriptionsClient.on("error", () => {
  console.log("callback called");
});
```

**Comment by der1igedon** [comment]
Thank you!
