### ISSUE TITLE
Can't resolve 'net' when moving from gqless to the gqty

### ISSUE THREAD

**Issue by chadgauth** [gqty-dev/gqty#1592]
Any ideas for this? I am just using Next.js and I do not want to use the server capability when running `yarn dev`
```
Failed to compile
./node_modules/ws/lib/sender.js:5:0
Module not found: Can't resolve 'net'

https://nextjs.org/docs/messages/module-not-found
```

Here's the stack:
```
Import trace for requested module:
./node_modules/ws/wrapper.mjs
./node_modules/gqty/Client/resolveSelections.mjs
./node_modules/gqty/index.mjs
./gqty/index.ts
./scenes/Greetings.tsx
./scenes/index.js
./pages/index.js
```

**Comment by vicary** [comment]
What is your installed version of `gqty` and `@gqty/react`?

**Comment by chadgauth** [comment]
Oh it looks like I have an alpha version that snuck in. It's working with the latest stable release. Despite following the documentation, I had to manually downgrade the packages, but it's working.

**Comment by vicary** [comment]
@chadgauth You are in fact encouraged to try out alpha versions, the issue is `yarn` tend disregard the `latest` tag in NPM, and sort the versions alphabetically, thus you installed an old alpha.

We are tweaking the GitHub action for NPM release such that it doesn't happen in the future, in the mean time you may remove the caret selector to have the actual latest alpha.
