### ISSUE TITLE
prepareReactRender is not a function.

### ISSUE THREAD

**Issue by ahmadmmughal** [gqty-dev/gqty#185]
Hi, i'm trying to follow this example here of gqty with nextjs: https://gqty.dev/docs/react/ssr

Getting the following error.

<img width="1050" alt="Screenshot 2021-10-04 at 3 51 54 AM" src="https://user-images.githubusercontent.com/9119707/135774103-b27d624b-a153-4850-a803-db54682c828c.png">

**Comment by PabloSzx** [comment]
the generated gqty client should have the react code, that exports the prepareReactRender function https://gqty.dev/docs/cli/config the config should have `react: true`, and you would have to remove the existing generated client, since the cli doesn't overwrite that file, only the schema.generated.ts
